pull_request_rules:
  - name: Auto merge pull requests
    conditions:
        - author=asahiocean
    actions:
      review:
        type: APPROVE
        message: Automatically approving
      merge:
        method: merge
