pull_request_rules:
   - name: Auto merge for Dependabot pull requests
     conditions:
      - author~=^dependabot(|-preview)\[bot\]$
     actions:
       review:
         type: APPROVE
         message: Automatically approving dependabot
       merge:
         method: merge
pull_request_rules:
  - name: Add "moved" label
    conditions:
      - head~=^moved
    actions:
      label:
          add:
          - moved
pull_request_rules:
    - name: Automatic approval PR
      conditions:
       - author=asahiocean
      actions:
        review:
          type: APPROVE
        merge:
          method: merge