pull_request_rules:
  - name: Auto merge pull requests
    conditions:
        - author=asahiocean
      or:
        - author=dependabot[bot]
    actions:
      review:
        type: APPROVE
        message: Automatically approving
      merge:
        method: merge
