name: Auto commit action
on: pull_request
jobs:
  git-auto-commit-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Success!
