name: Helper
on:
  pull_request:
    types: [created]
env:
  TOKEN: ${{ secrets.QLTVUTH5NF9D4MNF }}
  PR_NUM: ${{ github.event.pull_request.number }}
jobs:
  autolabel:
    if: ${{ github.actor }} == asahiocean
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "BRANCH=$(echo "${{ github.head_ref }}")" >> $GITHUB_ENV
      - name: Get list of labels
        run: |
          LIST=$(curl -X GET -u ${{ github.actor }}:${{ env.TOKEN }} \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/labels" \
          -H "Content-type: application/json" -k \
          -H "Accept: application/vnd.github.v3+json" | jq '.[] | .name')
          echo "LABELS=$(echo $LIST)" >> $GITHUB_ENV
      - name: Detect label
        run: |
          BRANCH=${{ env.BRANCH }}
          declare -a LABELS=(${{ env.LABELS }})
          for i in "${LABELS[@]}"
          do
             if [[ $BRANCH == *"$i"* ]]; then
                echo "LABEL=$i" >> $GITHUB_ENV
             fi
          done
      - name: Update branch label
        run: |
          gh pr edit "$PR_NUM" --add-label ${{ env.LABEL }}
          gh pr edit "$PR_NUM" --add-assignee "@me"
          gh pr edit "$PR_NUM" --add-assignee "sergfedotov"
  automerge:
      needs: autolabel
      runs-on: ubuntu-latest
      steps:
        - name: Auto merge after review
          run: |
            gh pr merge -m "$PR_URL"
